name: Lab 1, Task 2, Wine Inference Pipeline

on:
  schedule:
    # 01:00 UTC every day
    - cron: '15,45 * * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./lab1/task2/requirements.txt

    - name: Run Wine Batch Inference Pipeline
      working-directory: lab1/task2
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: python inference.py
